# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce82338d19644186263f01383052afaa04d48ec541972b23b386aaa227fc2819b78587b592e8fc71e0822096f8958bf7970c740371a8bcdb70bb10dc232a5fdd

test:
  secret_key_base: cc2b172160b42d40209cafffa54f64c4d2808bac6a8eb36091acb5433bdd82892968a4a647f2e468541b2ec272f06e797ddb4fbeec623f6caeb4555599c7af05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
